.\" Autorzy Marcin Cieślikowski Paweł Goździkowski Marek Jasiński
.TH DLM-client 1 "" "" "wersja 1.0"
.SH NAZWA
DLM-client \- Przykładowy program wykorzystujący DLM
.SH SKŁADNIA
.B DLM-client
.R <numer zasobu>
.R <typ blokady>
.R <timeout (w milisekundach)>
.R <czas uspienia (w sekundach)>
.R <liczba iteracji>
.br
.SH OPIS
Program 
.I DLM-client
zajmuje zasoby wykorzystując DLM. Po zajęciu zasobu program usypia się na
czas podany w argumencie. Program łączy się z DLM za pomocą kolejek nazwanych FIFO.
Kolejki FIFO znajdują się w katalogu /tmp/DLM. 

.SH ARGUMENTY
.TP
.B numer zasobu
argument ten przjmuje numer zasobu, który program ma zająć.
.TP
.B typ blokady
Wyróżniamy następujące typy blokad:
.nf
	0 - concurrent read(CR)
	1 - concurrent write(CW)
	2 - protected read(PR)
	3 - protected write(PW)
	4 - exclusive (EX)
.fi
.TP
.B timeout
Czas w milisekundach po którym, w przypadku niemożności założenia blokady na zasób, program zacznie wykonywać następne instrukcje. Wartość 0 oznacza nieskończony czas oczekiwania. Wartość -1 oznacza tryb bez blokowania,
-2 wykorzystuje funkcje try_lock, sprawdza czy może założyć blokade, ale jej nie zakłada.
.br
.TP
.B czas uspienia
Czas uśpienia programu po wykonaniu funkcji zakładajacej blokade na zasób(bez znaczenia czy funkcja założyła czy nie blokade).
.br
.TP
.B liczba iteracji
Liczba wykonań pętli w której program próbuje założyć blokadę na zasób.

.SH "ZOBACZ RÓWNIEŻ"
.BR DLMlib (3)
